//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenovo.WiFi.Client.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IHostedNetworkService")]
    public interface IHostedNetworkService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostedNetworkService/GetHostedNetworkName", ReplyAction="http://tempuri.org/IHostedNetworkService/GetHostedNetworkNameResponse")]
        string GetHostedNetworkName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostedNetworkService/SetHostedNetworkName", ReplyAction="http://tempuri.org/IHostedNetworkService/SetHostedNetworkNameResponse")]
        void SetHostedNetworkName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostedNetworkService/GetHostedNetworkKey", ReplyAction="http://tempuri.org/IHostedNetworkService/GetHostedNetworkKeyResponse")]
        string GetHostedNetworkKey();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostedNetworkService/SetHostedNetworkKey", ReplyAction="http://tempuri.org/IHostedNetworkService/SetHostedNetworkKeyResponse")]
        void SetHostedNetworkKey(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostedNetworkService/StartHostedNetwork", ReplyAction="http://tempuri.org/IHostedNetworkService/StartHostedNetworkResponse")]
        void StartHostedNetwork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostedNetworkService/StopHostedNetwork", ReplyAction="http://tempuri.org/IHostedNetworkService/StopHostedNetworkResponse")]
        void StopHostedNetwork();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHostedNetworkServiceChannel : Lenovo.WiFi.Client.Proxy.IHostedNetworkService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HostedNetworkServiceClient : System.ServiceModel.ClientBase<Lenovo.WiFi.Client.Proxy.IHostedNetworkService>, Lenovo.WiFi.Client.Proxy.IHostedNetworkService {
        
        public HostedNetworkServiceClient() {
        }
        
        public HostedNetworkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HostedNetworkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HostedNetworkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HostedNetworkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHostedNetworkName() {
            return base.Channel.GetHostedNetworkName();
        }
        
        public void SetHostedNetworkName(string name) {
            base.Channel.SetHostedNetworkName(name);
        }
        
        public string GetHostedNetworkKey() {
            return base.Channel.GetHostedNetworkKey();
        }
        
        public void SetHostedNetworkKey(string key) {
            base.Channel.SetHostedNetworkKey(key);
        }
        
        public void StartHostedNetwork() {
            base.Channel.StartHostedNetwork();
        }
        
        public void StopHostedNetwork() {
            base.Channel.StopHostedNetwork();
        }
    }
}
